name: Build and Deploy to GitHub Pages

# Triggers: push to main, manual dispatch
on:
  push:
    branches: [main]
  workflow_dispatch: # Manual trigger

# Minimal permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent concurrent deployments, allow in-progress to complete
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Bun for faster package management
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Cache Bun dependencies for faster builds
      - name: Get Bun cache directory
        id: bun-cache
        run: echo "dir=$(bun pm cache)" >> $GITHUB_OUTPUT

      - name: Setup Bun cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.bun-cache.outputs.dir }}
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Reproducible builds with frozen lockfile
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Vite SSG build to ./dist
      - name: Build project
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
